// frontend/src/app/features/auth/login/login.component.ts
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';

import { AuthService } from '../../../core/auth/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    ReactiveFormsModule,
    RouterLink,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatProgressSpinnerModule,
  ],
  templateUrl: './login.component.html',
})
export class LoginComponent {
  private readonly fb = inject(FormBuilder);
  private readonly auth = inject(AuthService);
  private readonly router = inject(Router);

  readonly loading = signal(false);
  readonly error = signal<string | null>(null);

  readonly form = this.fb.nonNullable.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', [Validators.required]],
  });

  submit(): void {
    if (this.form.invalid || this.loading()) {
      this.form.markAllAsTouched();
      return;
    }
    this.loading.set(true);
    this.error.set(null);

    this.auth.login(this.form.getRawValue()).subscribe({
      next: (res) => {
        this.loading.set(false);
        this.router.navigateByUrl(this.auth.homeForRole(res.rol));
      },
      error: (err) => {
        this.loading.set(false);
        this.error.set(err?.error?.message ?? 'No se pudo iniciar sesión. Verifica tus credenciales.');
      },
    });
  }
}

<div class="min-h-screen grid lg:grid-cols-2 bg-background">
  <!-- Panel de marca (izquierda) -->
  <div class="hidden lg:flex flex-col justify-between p-12 bg-brand-950 text-white relative overflow-hidden">
    <div class="flex items-center gap-2.5">
      <div class="size-10 rounded-xl bg-brand-500 grid place-items-center">
        <mat-icon class="text-white">restaurant</mat-icon>
      </div>
      <span class="text-lg font-semibold tracking-tight">FitPrep</span>
    </div>
    <div class="max-w-md">
      <h2 class="text-3xl font-semibold tracking-tight leading-tight">
        Nutrición fit, planificada y entregada.
      </h2>
      <p class="mt-4 text-sm text-white/70">
        Gestiona tu catálogo, planes semanales y producción de cocina desde un solo lugar.
      </p>
    </div>
    <div class="text-xs text-white/40">© 2026 FitPrep · SaaS multi-tenant</div>
  </div>

  <!-- Formulario (derecha) -->
  <div class="flex items-center justify-center p-6 sm:p-12">
    <div class="w-full max-w-sm">
      <div class="mb-8">
        <div class="text-[11px] font-semibold uppercase tracking-widest text-brand-600 mb-1.5">
          Bienvenido de nuevo
        </div>
        <h1 class="text-2xl font-semibold tracking-tight">Inicia sesión</h1>
        <p class="text-sm text-muted-foreground mt-1.5">Accede a tu panel de FitPrep.</p>
      </div>

      @if (error()) {
        <div class="mb-4 rounded-md border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">
          {{ error() }}
        </div>
      }

      <form [formGroup]="form" (ngSubmit)="submit()" class="space-y-4">
        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Correo electrónico</mat-label>
          <input matInput type="email" formControlName="email" placeholder="admin@fitprep.com" />
          <mat-icon matSuffix>mail</mat-icon>
          @if (form.controls.email.hasError('required') && form.controls.email.touched) {
            <mat-error>El correo es obligatorio</mat-error>
          }
          @if (form.controls.email.hasError('email')) {
            <mat-error>Correo no válido</mat-error>
          }
        </mat-form-field>

        <mat-form-field appearance="outline" class="w-full">
          <mat-label>Contraseña</mat-label>
          <input matInput type="password" formControlName="password" placeholder="••••••••" />
          <mat-icon matSuffix>lock</mat-icon>
          @if (form.controls.password.hasError('required') && form.controls.password.touched) {
            <mat-error>La contraseña es obligatoria</mat-error>
          }
        </mat-form-field>

        <button
          mat-flat-button
          color="primary"
          type="submit"
          class="w-full !h-11"
          [disabled]="loading()"
        >
          @if (loading()) {
            <mat-progress-spinner diameter="20" mode="indeterminate" />
          } @else {
            Entrar
          }
        </button>
      </form>

      <p class="text-center text-xs text-muted-foreground mt-6">
        ¿No tienes cuenta?
        <a routerLink="/register" class="text-brand-600 font-medium">Crear cuenta</a>
      </p>
    </div>
  </div>
</div>

// Downloads/Fitprep_Actual/FrontEnd/src/routes/login.tsx
import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { authService } from "../lib/api";

export const Route = createFileRoute("/login")({
  head: () => ({ meta: [{ title: "Ingresar — NutriFlow" }, { name: "description", content: "Accede a tu cuenta de NutriFlow." }] }),
  component: Login,
});

function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const navigate = useNavigate();

  const mutation = useMutation({
    mutationFn: () => authService.login(email, password),
    onSuccess: (data) => {
      if (data.token) {
        localStorage.setItem("token", data.token);
      }
      localStorage.setItem("usuario", JSON.stringify(data));

      // Redirigir según el rol del usuario
      if (data.rol === "ADMIN") {
        navigate({ to: "/admin" });
      } else if (data.rol === "TENANT") {
        navigate({ to: "/tenant" });
      } else {
        navigate({ to: "/athlete" });
      }
    },
    onError: (error: any) => {
      const msg = error.response?.data?.message || error.response?.data?.error || "Error al iniciar sesión. Verifica tus credenciales.";
      setErrorMessage(msg);
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setErrorMessage("");
    if (!email || !password) {
      setErrorMessage("Por favor, ingresa tu email y contraseña.");
      return;
    }
    mutation.mutate();
  };

  return (
    <AuthLayout title="Bienvenido de vuelta" subtitle="Ingresa con tu cuenta para continuar planificando.">
      <form onSubmit={handleSubmit} className="space-y-4">
        {errorMessage && (
          <div className="p-3 text-xs rounded bg-rose-50 text-rose-600 border border-rose-100">
            {errorMessage}
          </div>
        )}
        <Field 
          label="Email" 
          type="email" 
          placeholder="tu@email.com" 
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          disabled={mutation.isPending}
        />
        <Field 
          label="Contraseña" 
          type="password" 
          placeholder="••••••••" 
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          disabled={mutation.isPending}
          right={<Link to="/forgot" className="text-xs text-brand-600 hover:underline">¿Olvidaste?</Link>} 
        />
        <label className="flex items-center gap-2 text-xs text-muted-foreground">
          <input type="checkbox" className="rounded" /> Recordarme en este dispositivo
        </label>
        <button 
          type="submit" 
          disabled={mutation.isPending}
          className="w-full h-10 rounded-md bg-brand-500 text-white text-sm font-medium hover:bg-brand-600 disabled:opacity-50 flex items-center justify-center"
        >
          {mutation.isPending ? "Iniciando sesión..." : "Ingresar"}
        </button>
        <div className="flex items-center gap-3 text-[10px] uppercase text-muted-foreground">
          <div className="h-px flex-1 bg-border" />o<div className="h-px flex-1 bg-border" />
        </div>
        <button 
          type="button" 
          disabled={mutation.isPending}
          className="w-full h-10 rounded-md border border-border bg-card text-sm font-medium hover:bg-muted disabled:opacity-50"
        >
          Continuar con Google
        </button>
        <p className="text-center text-xs text-muted-foreground">
          ¿No tienes cuenta? <Link to="/register" className="text-brand-600 font-medium">Crear una</Link>
        </p>
      </form>
    </AuthLayout>
  );
}


export function AuthLayout({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) {
  return (
    <div className="min-h-screen grid lg:grid-cols-2 bg-background">
      <div className="hidden lg:flex flex-col justify-between p-12 bg-surface border-r border-border">
        <Link to="/" className="flex items-center gap-2">
          <div className="size-9 rounded-lg bg-brand-500 grid place-items-center"><div className="size-4 rounded-full border-2 border-white" /></div>
          <span className="font-semibold tracking-tight text-lg">NutriFlow</span>
        </Link>
        <div>
          <h2 className="text-3xl font-semibold tracking-tight leading-tight max-w-md text-balance">"Pasamos de Excel a NutriFlow y redujimos el desperdicio en un 38%."</h2>
          <div className="mt-6 flex items-center gap-3">
            <div className="size-10 rounded-full bg-brand-100 grid place-items-center text-brand-700 font-semibold">LR</div>
            <div>
              <div className="text-sm font-medium">Laura Restrepo</div>
              <div className="text-xs text-muted-foreground">CEO · FitKitchen Madrid</div>
            </div>
          </div>
        </div>
        <div className="text-xs text-muted-foreground">© 2026 NutriFlow Cloud Systems</div>
      </div>
      <div className="flex items-center justify-center p-8">
        <div className="w-full max-w-sm">
          <h1 className="text-2xl font-semibold tracking-tight">{title}</h1>
          <p className="mt-1.5 text-sm text-muted-foreground">{subtitle}</p>
          <div className="mt-8">{children}</div>
        </div>
      </div>
    </div>
  );
}

export function Field({ label, right, ...rest }: { label: string; right?: React.ReactNode } & React.InputHTMLAttributes<HTMLInputElement>) {
  return (
    <div>
      <div className="flex items-center justify-between mb-1.5">
        <label className="text-xs font-medium">{label}</label>
        {right}
      </div>
      <input {...rest} className="w-full h-10 px-3 rounded-md border border-input bg-card text-sm focus:outline-none focus:ring-2 focus:ring-ring/30 focus:border-ring" />
    </div>
  );
}
